name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Maven Package
        run: mvn -B clean compile package -DskipTests
        
  push_image:
    needs: build
    name: Push image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Open Web Client Directory
        run: |
            ls -la
            cd application
            
      - name: Docker Build and Push to DockerHub application microservices
        uses: docker/build-push-action@v2
        with:
          run: |
               ls -la
               cd application
          context: application
          file: application/Dockerfile
          push: true
          tags: sladkkov/application:latest

          
     
          
  
 
